<?php if ($status = $this->verifyCredentials()): ?>
    <script type="text/javascript">
        //<![CDATA[
            var thistwitterverify = new twitterverify();
            thistwitterverify.status = "<?php echo $status; ?>";
        <?php if ($status == 'ready'): ?>
            thistwitterverify.reseturl = "<?php echo Mage::helper('adminhtml')->getUrl('twitterreader/callback/reset'); ?>";
        <?php elseif ($status == 'verify_credentials'): ?>
            thistwitterverify.callbackurl = "<?php echo Mage::getStoreConfig('twitterreader/configuration/callback_url'); ?>";
            thistwitterverify.reseturl = "<?php echo Mage::helper('adminhtml')->getUrl('twitterreader/callback/reset'); ?>";
        <?php elseif ($status == 'bad_verify'): ?>
            thistwitterverify.reseturl = "<?php echo Mage::helper('adminhtml')->getUrl('twitterreader/callback/reset'); ?>";
        <?php elseif ($status == 'problem'): ?>
            thistwitterverify.reseturl = "<?php echo Mage::helper('adminhtml')->getUrl('twitterreader/callback/reset'); ?>";
        <?php elseif (is_int($status)): ?>
            thistwitterverify.status = "exceeded";
            thistwitterverify.reset = "<?php echo date('H:i:s', $status); ?>";
        <?php elseif ($status == 'bad_callback'): ?>
            thistwitterverify.reseturl = "<?php echo Mage::helper('adminhtml')->getUrl('twitterreader/callback/reset'); ?>";
        <?php endif; ?>
        //]]>
        </script>
<?php endif; ?>